version: '3.9'
services:
  client:
    build: .
    image: prefect-client:1.1
    container_name: prefect_client
    command: [ "python3", "/usr/app/deployment.py" ]

    volumes:
      - /srv/docker/prefect/flows:/flows
      - ./app:/usr/app:ro
    environment:
      - PREFECT_API_URL=http://172.17.0.1:4200/api
