version: '3.9'
services:
  agent:
    build: .
    image: prefect-agent:1.1
    container_name: prefect_agent
    restart: always
    entrypoint: [ "prefect", "agent", "start", "-q", "WORK_QUEUE_NAME" ]
    environment:
      - PREFECT_API_URL=http://172.17.0.1:4200/api
    volumes:
      - /srv/docker/prefect/flows:/root/.prefect/flows
      - /srv/docker/prefect/flows:/flows
    profiles: [ "agent" ]

volumes:
  prefect_flows: # So the volume where you save the flows must be shared among your client and your agent(s).
